/*
 * params_config.h
 * Version: 2.1
 * Model: TestCartPend1
 *
 * Per-model configuration for read_params_sfcn.
 * THIS is the only file that differs between models.
 *
 * PARAM_NAMES : JSON key names (case sensitive, must match params.json)
 * PARAM_PTRS  : pointers to the matching ExportedGlobal C variables
 *
 * Both arrays must stay in the same order and same length.
 *
 * To add a param:
 *   1. Add to InitFcn:  newparam = Simulink.Parameter(0.0);
 *                       newparam.StorageClass = 'ExportedGlobal';
 *   2. Add name to PARAM_NAMES below
 *   3. Add &newparam to PARAM_PTRS below
 *   4. Recompile MEX and rebuild model
 *
 * Current output mapping:
 *   "kp" → kp (PID Proportional)
 *   "ki" → ki (PID Integral)
 *   "kd" → kd (PID Derivative)
 */



#ifndef PARAMS_CONFIG_H
#define PARAMS_CONFIG_H

#define PARAMS_PATH "/home/owlsley/picontrol/params/params.json"

/* ------------------------------------------------------------------
 * On Windows (MEX build): define stub variables so the linker is happy.
 * On Pi (Coder build):    use extern to reference the ExportedGlobals
 *                         generated by Simulink Coder.
 * ------------------------------------------------------------------ */
#ifdef MATLAB_MEX_FILE
    /* MEX simulation build — define local stubs */
    static double kp = 1.0;
    static double ki = 0.0;
    static double kd = 0.0;
#else
    /* Coder standalone build — reference ExportedGlobal variables */
    extern double kp;
    extern double ki;
    extern double kd;
#endif

/* JSON key names — must match params.json exactly */
static const char *PARAM_NAMES[] = {
    "kp",
    "ki",
    "kd"
};

/* Pointers to variables — same order as PARAM_NAMES */
static double *PARAM_PTRS[] = {
    &kp,
    &ki,
    &kd
};

#define N_PARAMS (sizeof(PARAM_NAMES) / sizeof(PARAM_NAMES[0]))

#endif /* PARAMS_CONFIG_H */