# Generated by Django 4.2.28 on 2026-03-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
