# Generated by Django 4.2.26 on 2025-12-02 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatlabApp', '0002_command_user_message_user_sensordata_user'),
    ]

    operations = [
	migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to=settings.AUTH_USER_MODEL
            ),
        )
    ]
