# Generated by Django 4.2.28 on 2026-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatlabApp', '0005_controllock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllock',
            name='user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
