# Generated by Django 4.2.28 on 2026-03-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatlabApp', '0006_alter_controllock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
